version: '3.7'

x-volumes:
  &default-volume
  - "./files:/app/files"

services:
  go:
    build: go
    volumes: *default-volume

  java:
    build: java
    volumes: *default-volume

  js:
    build: js
    volumes: *default-volume

  php:
    build: php
    volumes: *default-volume
